Build out octokitgithub adapter (WIP) (#11)
* Call the getMembersOf method from the unit test

Co-authored-by: marjuhirsh <marjuhirsh@users.noreply.github.com>
Co-authored-by: Arti M <artismarti@users.noreply.github.com>
Co-authored-by: Meena <aneemqah@users.noreply.github.com>

* Add dependency on OctoKit library

Co-authored-by: marjuhirsh <marjuhirsh@users.noreply.github.com>
Co-authored-by: Arti M <artismarti@users.noreply.github.com>
Co-authored-by: Meena <aneemqah@users.noreply.github.com>
Co-authored-by: Blaise Pabon <blaise@gmail.com>

* WIP: next step is to get the auth token figured out because we get:
```
1) OctokitGithub
       gets members of a team:
     Error: Parameter token or opts.auth is required
      at Object.getAuthString (node_modules/@actions/github/src/internal/utils.ts:10:11)
      at Object.getOctokitOptions (node_modules/@actions/github/src/utils.ts:38:22)
      at getOctokit (node_modules/@actions/github/src/github.ts:19:21)
      at /Users/bpabon/src/inactive-contributor-bot/src/OctokitGithub.test.ts:7:31
      at Generator.next (<anonymous>)
      at /Users/bpabon/src/inactive-contributor-bot/src/OctokitGithub.test.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (src/OctokitGithub.test.ts:4:12)
      at Context.<anonymous> (src/OctokitGithub.test.ts:6:43)
      at processImmediate (node:internal/timers:466:21)
      ```
      Co-authored-by: Marju Hirsh <marjutubli@gmail.com>

* Update package-lock

* Starting to make our first API call

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Fixed the type of the Octokit object

Co-authored-by: Arti M <111852+artismarti@users.noreply.github.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Got the test to fail properly on a bad token

Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>
Co-authored-by: Arti M <111852+artismarti@users.noreply.github.com>

* Parse the result of calling listMembersInOrg to return the names of the team members

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>

* Remove hard-coded org

Closes #16

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>

* // TODO: build a request with the pattern: https://api.github.com/repos/{user}/{repo}commits/master
    // Possible suggestion in https://stackoverflow.com/a/61548243/11799079 for get last commit
    // To be implemented.

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Karla Justen<justen.karla@gmail.com>

* Add failing test for getLastCommitBy

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Breaking everything!

We decided to replace getLastCommitBy with a boolean hasCommittedSince which is much simpler. We're half way through the implementaion, so some of the code which was using the original method will need to be updated.

Look at the TODOs and build errors when you run `npm run test` for clues!

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Implement truthy test case for hasCommittedSince

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Extend the FakeGithub implementation.

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Prepare to remove hard coded repo.

Our intention is to keep the behaviour .
Later we will retrieve a list of repos from the API and loop through the list.

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>

* Commit javascript changes

Co-authored-by: Kate Dames <funficient@users.noreply.github.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>
Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Separate FakeGitHub into its own file

Co-authored-by: Kate Dames <funficient@users.noreply.github.com>
Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Lauren <laurenlewis@users.noreply.github.com>

* Implement hasCommittedSince on FakeGitHub

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>

* Add TODO about what to do next

Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>

* Fix linting

* Replace getLastCommitBy with hasCommitedSince in core logic

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Clean up after replacing getLastCommitBy

* Moved Commit type into FakeGitHubClient
* Renamed our Github interface to GithubClient so it's clearly disambiguated from Github's own type.

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Rename things

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Commit compiled javascript

* List all git repos in org in hasCommittedSince

Co-authored-by: Arianna Cooper <aricooper55@gmail.com>

* Tidy up TODOs

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Add a failing test for addUserToTeam

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Ensure we pick up typescript build errors in the src folder

* Upgrade package

* Fix casing

* Clear members of test team before adding someone

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Refactor

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Fix a missing await

Co-authored-by: Blaise Pabon <blaise@gmail.com>

* Add GITHUB_TOKEN env var to CI

* Use a PAT for Octokit in the tests

* Give the tests a little more time

Co-authored-by: Blaise Pabon <blaise@gmail.com>

Co-authored-by: marjuhirsh <marjuhirsh@users.noreply.github.com>
Co-authored-by: Arti M <artismarti@users.noreply.github.com>
Co-authored-by: Meena <aneemqah@users.noreply.github.com>
Co-authored-by: Blaise Pabon <blaise@gmail.com>
Co-authored-by: Arti M <111852+artismarti@users.noreply.github.com>
Co-authored-by: Olle Jonsson <olle.jonsson@gmail.com>
Co-authored-by: Kate Dames <kate.funficient@gmail.com>
Co-authored-by: Kate Dames <funficient@users.noreply.github.com>
Co-authored-by: Lauren <laurenlewis@users.noreply.github.com>
Co-authored-by: Arianna Cooper <aricooper55@gmail.com>